<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DpbResponsibility" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://www.sella.it/schema/Crediti/DpbResponsibility" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/DpbResponsibility_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DpbResponsibility"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/getResponsibility.xsd"/>
            <oracle-xsl-mapper:rootElement name="getResponsibilityResponse" namespace="http://www.sella.it/schema/Crediti/DpbResponsibility"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU JUN 21 19:19:44 IST 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:getResponsibilityResponse>
         <tns:CAPO_SUCCURSALE>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:CAPO_SUCCURSALE"/>
         </tns:CAPO_SUCCURSALE>
         <tns:VICE_CAPO_SUCCURSALE>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:VICE_CAPO_SUCCURSALE"/>
         </tns:VICE_CAPO_SUCCURSALE>
         <tns:CAPO_DISTRETTO>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:CAPO_DISTRETTO"/>
         </tns:CAPO_DISTRETTO>
         <tns:VICE_CAPO_DISTRETTO>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:VICE_CAPO_DISTRETTO"/>
         </tns:VICE_CAPO_DISTRETTO>
         <tns:CAPO_AREA>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:CAPO_AREA"/>
         </tns:CAPO_AREA>
         <tns:VICE_CAPO_AREA>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:VICE_CAPO_AREA"/>
         </tns:VICE_CAPO_AREA>
         <tns:CAPO_AREA_BUSINESS>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:CAPO_AREA_BUSINESS"/>
         </tns:CAPO_AREA_BUSINESS>
         <tns:RESP_EROGAZIONE_CREDITO>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:RESP_EROGAZIONE_CREDITO"/>
         </tns:RESP_EROGAZIONE_CREDITO>
         <tns:CREDITI_E_SMALLBUSINESS>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:CREDITI_E_SMALLBUSINESS"/>
         </tns:CREDITI_E_SMALLBUSINESS>
         <tns:CREDITI_E_SMALLBUSIN_DEDICATO>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:CREDITI_E_SMALLBUSIN_DEDICATO"/>
         </tns:CREDITI_E_SMALLBUSIN_DEDICATO>
         <tns:FAMILY>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:FAMILY"/>
         </tns:FAMILY>
         <tns:FAMILY_DEDICATO>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:FAMILY_DEDICATO"/>
         </tns:FAMILY_DEDICATO>
         <tns:AFFLUENT>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:AFFLUENT"/>
         </tns:AFFLUENT>
         <tns:AFFLUENT_DEDICATO>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:AFFLUENT_DEDICATO"/>
         </tns:AFFLUENT_DEDICATO>
         <tns:DI_SUPPORTO>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:DI_SUPPORTO"/>
         </tns:DI_SUPPORTO>
         <tns:ESTERO>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:ESTERO"/>
         </tns:ESTERO>
         <tns:CFD>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:CFD"/>
         </tns:CFD>
         <tns:CSF>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:CSF"/>
         </tns:CSF>
         <tns:CFI>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:CFI"/>
         </tns:CFI>
         <tns:CCR>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:CCR"/>
         </tns:CCR>
         <tns:UNIT_CODE>
            <xsl:value-of select="/ns0:OutputParameters/ns0:GET_RESPONSIBILITY/ns0:UNIT_CODE"/>
         </tns:UNIT_CODE>
      </tns:getResponsibilityResponse>
   </xsl:template>
</xsl:stylesheet>
